//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PduSerializer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PduSerializer.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input stream must be a BitStream for a bitwise serialization..
        /// </summary>
        internal static string BitStreamRequiredForBitwiseSerialization {
            get {
                return ResourceManager.GetString("BitStreamRequiredForBitwiseSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not supported for bitwise serialization. Types supported: Boolean[] or BitArray..
        /// </summary>
        internal static string BitwiseSerializationDoesNotSupportMemberType {
            get {
                return ResourceManager.GetString("BitwiseSerializationDoesNotSupportMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The declared list size is diffrent than actual size. Declared size is {0}, but actual size is {1}..
        /// </summary>
        internal static string DeclaredListSizeIsDiffrentThanActualSize {
            get {
                return ResourceManager.GetString("DeclaredListSizeIsDiffrentThanActualSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; has the same position a previous field in the type, field order must be deterministic..
        /// </summary>
        internal static string DuplicateFieldOrderErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateFieldOrderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of array or list must be positive..
        /// </summary>
        internal static string ListSizeOutOfRangeErrorMessage {
            get {
                return ResourceManager.GetString("ListSizeOutOfRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member {0} was not found in type {1}..
        /// </summary>
        internal static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; cannot be serialized, add PduMessageAttribute on the type..
        /// </summary>
        internal static string MissingPduMessageAttributeErrorMessage {
            get {
                return ResourceManager.GetString("MissingPduMessageAttributeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No serialization was configured to type &apos;{0}&apos;..
        /// </summary>
        internal static string NoDescriptorForTypeErrorMessage {
            get {
                return ResourceManager.GetString("NoDescriptorForTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field {0} of type {1} is not a serializable type..
        /// </summary>
        internal static string NotSerializableTypeErrorMessage {
            get {
                return ResourceManager.GetString("NotSerializableTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of string must be positive..
        /// </summary>
        internal static string PaddingStringSizeOutOfRangeErrorMessage {
            get {
                return ResourceManager.GetString("PaddingStringSizeOutOfRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serialization configuration is sealed. Cannot modify mappings..
        /// </summary>
        internal static string SealedConfigurationErrorMessage {
            get {
                return ResourceManager.GetString("SealedConfigurationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String was longer then expected size {0}..
        /// </summary>
        internal static string TooLongStringErrorMessage {
            get {
                return ResourceManager.GetString("TooLongStringErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum type {0} does not have a serializer..
        /// </summary>
        internal static string UnsupportedEnumValueTypeErrorMessage {
            get {
                return ResourceManager.GetString("UnsupportedEnumValueTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not an array or list. Types supported: Array, List&lt;T&gt;, IList&lt;T&gt;, ICollection&lt;T&gt; and IEnumerable&lt;T&gt;..
        /// </summary>
        internal static string UnsupportedListType {
            get {
                return ResourceManager.GetString("UnsupportedListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member is not a property or a field..
        /// </summary>
        internal static string UnsupportedMemberType {
            get {
                return ResourceManager.GetString("UnsupportedMemberType", resourceCulture);
            }
        }
    }
}
